spring.application:
  name: board
  devtools:
    restart:
      enabled: false

# server port
server:
  port: 8080

# HikariCP 로그 활성화 (관련 로그를 디버그 레벨로 출력)
logging:
  level:
    com.zaxxer.hikari: DEBUG

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leeaain?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: 1234
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 10000 # 유휴 연결 유지시간 (밀리초)
      max-lifetime: 30000 # 연결 최대 수명 (밀리초)
      housekeeping-period-ms: 15000 # Housekeeper 작업이 실행되는 주기 (밀리초)
      auto-commit: false # 자동 커밋 설정
      # housekeeper: 연결 유효성 검사(연결 풀 점검), 유휴 연결 검증 & 제세팅
      # 이 작업이 실행되면 시간이 만료되어서 제거되었던 유휴연결을 최소유휴연결 수에 맞춰 다시 생성함.

# mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml
